# If you are only using Pages + D1, you only need the below in your wrangler.toml to interact with D1 locally.
[[d1_databases]]
binding = "SVELTELO_DB" # Should match preview_database_id
database_name = "pongelo-preview-db"
database_id = "<database_id>" # wrangler d1 info YOUR_DATABASE_NAME
preview_database_id = "SVELTELO_DB" # Required for Pages local development